plugins {
    id 'com.gradleup.shadow'
}

def generatedResources = file("src/generated")

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

loom {
    forge {
        mixinConfig "left_forgotten_common.mixins.json"
    }

    mixin {
        useLegacyMixinAp = true
    }

    runs {
        data {
            data()
            programArgs "--all", "--mod", "left_forgotten"
            programArgs "--output", generatedResources.absolutePath
        }
    }
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${rootProject.mixinextrasVersion}"))
    include(implementation("io.github.llamalad7:mixinextras-forge:${rootProject.mixinextrasVersion}"))
    compileOnly(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${rootProject.mixinsquaredVersion}"))
    implementation(include("com.github.bawnorton.mixinsquared:mixinsquared-forge:${rootProject.mixinsquaredVersion}"))

    modImplementation "dev.architectury:architectury-forge:$rootProject.architectury_api_version"
    modImplementation "me.shedaniel.cloth:cloth-config-forge:11.1.136"

    modCompileOnly 'com.github.Nostalgica-Reverie.Nostalgic-Tweaks:NostalgicTweaks-forge:1.20.1-SNAPSHOT'

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')
}

processResources {
    inputs.property 'mod_version', project.mod_version
    inputs.property 'minecraft_version', project.minecraft_version
    inputs.property 'forge_version_range', project.forge_version_range
    inputs.property 'architectury_api_version', project.architectury_api_version

    filesMatching('META-INF/mods.toml') {
        expand mod_version: inputs.properties.mod_version,
                forge_version_range: inputs.properties.forge_version_range,
                minecraft_version: inputs.properties.minecraft_version,
                architectury_api_version: inputs.properties.architectury_api_version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
