modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/JustMili0/LeftForgotten/issues"
license = "All Rights Reserved"

[[mods]]
modId = "left_forgotten"
version = "${mod_version}"
displayName = "Left Forgotten"
description = "Once glory days of Minecraft, now buried beneath the void. Minecraft Alpha is still there, but left and abandoned ages ago."
authors = "JustMili"
credits = "BluSpring, NBSurprise"
logoFile = "icon.png"

[[dependencies.left_forgotten]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version_range},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.left_forgotten]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.left_forgotten]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "left_forgotten_common.mixins.json"

[[mixins]]
config = "left_forgotten_neoforge.mixins.json"